# Generated by Django 5.0.6 on 2024-07-18 21:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=50, verbose_name='status')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Name')),
                ('category', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('bagel', 'Bagel')], db_index=True, default='others', max_length=15, verbose_name='Categories')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
